### ISSUE TITLE
请问后端数据库的表格形式是什么样的呀？

### ISSUE THREAD

**Issue by dst111dst** [s649821022/epidemic#1]
抱歉，打扰了，我下载了前端和后端仓库，同时运行时，login界面显示“账号或密码错误”（我首先运行了`python manage.py createsuperuser`，创建的超级用户为123456，密码为123456），此时，django的debug页面`http://127.0.0.1:8000/api/v1/auth/login/` 显示如下：

<img width="765" alt="截屏2022-11-15 上午10 23 55" src="https://user-images.githubusercontent.com/72456015/201811082-d66ea78d-0797-4218-896c-ceec1a4225fb.png">

请问后端对数据的验证是在哪里实现的呀？非常感谢分享和回复

**Comment by s649821022** [comment]
原因应该是数据库没创建

**Comment by dst111dst** [comment]
请问用到的数据库database name和table name可以在哪里看到呢？谢谢回复🙏😢

**Comment by s649821022** [comment]
先使用数据库管理工具创建1个数据库，我默认名称是epidemic
然后执行下面两条命令
python manage.py makemigrations  # 生成数据库迁移脚本
python manage.py migrate  # 执行数据库迁移脚本
之后你去数据库里看看有没有表生成

**Comment by dst111dst** [comment]
谢谢！！

**Comment by s649821022** [comment]
在config/settings/local.py下
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "epidemic",  # noqa F405
        "USER": "root",
        "PASSWORD": "123456",
        "HOST": "127.0.0.1",
        "PORT": 3306,
    }
}

**Comment by dst111dst** [comment]
好的，谢谢谢谢！！！感谢回复！！！
