### ISSUE TITLE
请问django的debug页面，为什么有的显示方法允许post、但是没有相应的表单呢？

### ISSUE THREAD

**Issue by dst111dst** [s649821022/epidemic#2]
不好意思又打扰了..我们发现像login这样的页面，是可以显式地表现表单的：

<img width="764" alt="截屏2022-11-28 下午9 29 38" src="https://user-images.githubusercontent.com/72456015/204290043-15080559-0c1b-4b0b-b249-8ba2608e045a.png">

--------------------------------------
但是在vaccinate对应的这些路由下，debug界面是没有显式出现表单的：

<img width="560" alt="截屏2022-11-28 下午9 29 56" src="https://user-images.githubusercontent.com/72456015/204290322-f0cf772b-c4ef-4d41-879b-91d84d3bd34c.png">

请问这是因为后端的相应model下没有显式写出post方法的原因吗？

感谢解答！实在是太感谢了😭

**Comment by s649821022** [comment]
> 不好意思又打扰了..我们发现像login这样的页面，是可以显式地表现表单的：
> 
> <img alt="截屏2022-11-28 下午9 29 38" width="764" src="https://user-images.githubusercontent.com/72456015/204290043-15080559-0c1b-4b0b-b249-8ba2608e045a.png">
> 
> 但是在vaccinate对应的这些路由下，debug界面是没有显式出现表单的：
> 
> <img alt="截屏2022-11-28 下午9 29 56" width="560" src="https://user-images.githubusercontent.com/72456015/204290322-f0cf772b-c4ef-4d41-879b-91d84d3bd34c.png">
> 
> 请问这是因为后端的相应model下没有显式写出post方法的原因吗？
> 
> 感谢解答！实在是太感谢了😭

首先这个界面是DRF内置的渲染器写的，没有你说的那种表单是因为没有认证通过，第一个是登录接口不需要认证，这个界面其实不用太关注，如果你想看接口文档的话，可以访问http://127.0.0.1:8000/swagger/，能看到接口文档

**Comment by s649821022** [comment]
> 不好意思又打扰了..我们发现像login这样的页面，是可以显式地表现表单的：
> 
> <img alt="截屏2022-11-28 下午9 29 38" width="764" src="https://user-images.githubusercontent.com/72456015/204290043-15080559-0c1b-4b0b-b249-8ba2608e045a.png">
> 
> 但是在vaccinate对应的这些路由下，debug界面是没有显式出现表单的：
> 
> <img alt="截屏2022-11-28 下午9 29 56" width="560" src="https://user-images.githubusercontent.com/72456015/204290322-f0cf772b-c4ef-4d41-879b-91d84d3bd34c.png">
> 
> 请问这是因为后端的相应model下没有显式写出post方法的原因吗？
> 
> 感谢解答！实在是太感谢了😭

首先这个界面是DRF内置的渲染器写的，没有你说的那种表单是因为没有认证通过，第一个是登录接口不需要认证，这个界面其实不用太关注，如果你想看接口文档的话，可以访问http://127.0.0.1:8000/swagger/，能看到接口文档

**Comment by dst111dst** [comment]
收到回复，太感谢了！
